import os
import csv
import json

PROJECT_DIR = r"C:\Mine\porto\profildesainhu\Desa Air Putih Digital Experience"
FINAL_CSV = os.path.join(PROJECT_DIR, "docs", "FINAL_PHOTO_SELECTION.csv")
GALLERY_TS = os.path.join(PROJECT_DIR, "src", "content", "gallery.ts")

gallery_photos = []

with open(FINAL_CSV, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        # Include if primary is GALLERY, or even secondary is GALLERY
        if row['primary_page'] == 'GALLERY' or row['secondary_page'] == 'GALLERY':
            # Map visual tier or reason to some category
            category = 'Masyarakat'
            if 'KKN' in row['primary_page'] or 'KKN' in row['secondary_page']:
                category = 'KKN'
            elif 'PENDIDIKAN' in row['primary_page'] or 'PENDIDIKAN' in row['secondary_page']:
                category = 'Pendidikan'
            elif 'KEGIATAN' in row['primary_page'] or 'KEGIATAN' in row['secondary_page']:
                category = 'Kegiatan'
            elif 'BACKGROUND' in row['primary_page'] or 'HERO' in row['primary_page']:
                category = 'Kegiatan'
            elif 'GALLERY' in row['primary_page']:
                category = 'Masyarakat'
                
            gallery_photos.append({
                "id": row['id'],
                "src": f"/images/final/{row['filename']}",
                "alt": row['short_reason'],
                "caption": row['short_reason'],
                "category": category,
                "date": "2026"
            })

ts_content = f"""// Auto-generated by script
export type PhotoCategory = 'Semua' | 'Masyarakat' | 'Kegiatan' | 'Pendidikan' | 'KKN';

export interface Photo {{
  id: string;
  src: string;
  alt: string;
  caption: string;
  category: PhotoCategory;
  date?: string;
}}

export const GALLERY_PHOTOS: Photo[] = {json.dumps(gallery_photos, indent=2)};
"""

with open(GALLERY_TS, "w", encoding="utf-8") as f:
    f.write(ts_content)

print(f"Generated {GALLERY_TS} with {len(gallery_photos)} photos.")
