// Auto-generated by script from FINAL_PHOTO_SELECTION.csv
export type PhotoCategory = 'Semua' | 'Masyarakat' | 'Kegiatan' | 'Pendidikan' | 'KKN';

export interface Photo {
  id: string;
  src: string;
  alt: string;
  caption: string;
  category: PhotoCategory;
  orientation?: 'landscape' | 'portrait' | 'square';
  date?: string;
}

export const GALLERY_PHOTOS: Photo[] = [
  {
    "id": "002",
    "src": "/images/background/background_01.webp",
    "alt": "Tree branches. Good texture.",
    "caption": "Tree branches. Good texture.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "004",
    "src": "/images/background/background_02.webp",
    "alt": "Tree silhouette against sky. Perfect for text overlay.",
    "caption": "Tree silhouette against sky. Perfect for text overlay.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "008",
    "src": "/images/profil/profil_story_02.webp",
    "alt": "Nice candid portrait showing village environment.",
    "caption": "Nice candid portrait showing village environment.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "012",
    "src": "/images/kkn/kkn_activity_07.webp",
    "alt": "Gotong royong activity (sweeping). Directly shows pengabdian.",
    "caption": "Gotong royong activity (sweeping). Directly shows pengabdian.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "014",
    "src": "/images/gallery/landscape/gallery_landscape_09.webp",
    "alt": "Little girl peeking. Great human interest.",
    "caption": "Little girl peeking. Great human interest.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "016",
    "src": "/images/supporting/supporting_01.webp",
    "alt": "Boy holding green flag. Good leading lines and action.",
    "caption": "Boy holding green flag. Good leading lines and action.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "019",
    "src": "/images/kkn/kkn_activity_08.webp",
    "alt": "Carrying items together. Teamwork vibe.",
    "caption": "Carrying items together. Teamwork vibe.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "022",
    "src": "/images/gallery/landscape/gallery_landscape_10.webp",
    "alt": "Portrait under tree.",
    "caption": "Portrait under tree.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "030",
    "src": "/images/profil/profil_content_06.webp",
    "alt": "Kids lined up outdoors, good documentation of activity.",
    "caption": "Kids lined up outdoors, good documentation of activity.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "032",
    "src": "/images/kkn/kkn_activity_03.webp",
    "alt": "Teachers and KKN interacting with students.",
    "caption": "Teachers and KKN interacting with students.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "042",
    "src": "/images/profil/profil_content_07.webp",
    "alt": "Uniformed kids, shows school environment.",
    "caption": "Uniformed kids, shows school environment.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "060",
    "src": "/images/profil/profil_content_08.webp",
    "alt": "Active crafting (volcano project). Great storytelling.",
    "caption": "Active crafting (volcano project). Great storytelling.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "072",
    "src": "/images/profil/profil_content_09.webp",
    "alt": "Proud kid showing artwork.",
    "caption": "Proud kid showing artwork.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "077",
    "src": "/images/gallery/landscape/gallery_landscape_04.webp",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "083",
    "src": "/images/gallery/landscape/gallery_landscape_05.webp",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "091",
    "src": "/images/gallery/landscape/gallery_landscape_06.webp",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "107",
    "src": "/images/kkn/kkn_activity_04.webp",
    "alt": "Great interaction between KKN members and kids.",
    "caption": "Great interaction between KKN members and kids.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "119",
    "src": "/images/home/home_hero_01.webp",
    "alt": "Large vibrant group shot outdoors. Good energy.",
    "caption": "Large vibrant group shot outdoors. Good energy.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "134",
    "src": "/images/kkn/kkn_activity_05.webp",
    "alt": "Large group documentation shot on porch.",
    "caption": "Large group documentation shot on porch.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "157",
    "src": "/images/kkn/kkn_activity_06.webp",
    "alt": "KKN members posing outdoors with kids.",
    "caption": "KKN members posing outdoors with kids.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "160",
    "src": "/images/gallery/landscape/gallery_landscape_07.webp",
    "alt": "Fun meta photo of KKN taking picture of a kid on slide.",
    "caption": "Fun meta photo of KKN taking picture of a kid on slide.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "166",
    "src": "/images/gallery/landscape/gallery_landscape_08.webp",
    "alt": "Kid on slide. Playful.",
    "caption": "Kid on slide. Playful.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "173",
    "src": "/images/gallery/landscape/gallery_landscape_11.webp",
    "alt": "Close up selfie with kids. Very dynamic and fun.",
    "caption": "Close up selfie with kids. Very dynamic and fun.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "176",
    "src": "/images/gallery/landscape/gallery_landscape_12.webp",
    "alt": "Pinning a badge. Detailed action shot.",
    "caption": "Pinning a badge. Detailed action shot.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "183",
    "src": "/images/home/home_hero_03.webp",
    "alt": "Excellent close-up portrait of smiling boy. Strong emotional connection.",
    "caption": "Excellent close-up portrait of smiling boy. Strong emotional connection.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "187",
    "src": "/images/profil/profil_content_13.webp",
    "alt": "Boy focused on coloring. Good composition.",
    "caption": "Boy focused on coloring. Good composition.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "197",
    "src": "/images/kkn/kkn_activity_10.webp",
    "alt": "Group shot displaying finished artwork.",
    "caption": "Group shot displaying finished artwork.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "209",
    "src": "/images/profil/profil_content_14.webp",
    "alt": "Top-down view of kids coloring on the floor. Immersive.",
    "caption": "Top-down view of kids coloring on the floor. Immersive.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "227",
    "src": "/images/kkn/kkn_activity_11.webp",
    "alt": "Another good group documentation.",
    "caption": "Another good group documentation.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "250",
    "src": "/images/gallery/landscape/gallery_landscape_14.webp",
    "alt": "Guy posing on stairs.",
    "caption": "Guy posing on stairs.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "255",
    "src": "/images/profil/profil_story_03.webp",
    "alt": "Another warm portrait for humanizing the about page.",
    "caption": "Another warm portrait for humanizing the about page.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "258",
    "src": "/images/gallery/landscape/gallery_landscape_15.webp",
    "alt": "Girl smiling on playground.",
    "caption": "Girl smiling on playground.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "320",
    "src": "/images/profil/profil_content_12.webp",
    "alt": "Close up of kids making kolase.",
    "caption": "Close up of kids making kolase.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "325",
    "src": "/images/home/home_hero_02.webp",
    "alt": "Unique top-down angle of kids crafting. Good for creative layout.",
    "caption": "Unique top-down angle of kids crafting. Good for creative layout.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "393",
    "src": "/images/profil/profil_content_10.webp",
    "alt": "Teaching in front of the class. Essential education shot.",
    "caption": "Teaching in front of the class. Essential education shot.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "402",
    "src": "/images/profil/profil_content_11.webp",
    "alt": "Boys at desks paying attention.",
    "caption": "Boys at desks paying attention.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "410",
    "src": "/images/kkn/kkn_activity_09.webp",
    "alt": "Candid shot of KKN members relaxing by bikes.",
    "caption": "Candid shot of KKN members relaxing by bikes.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "420",
    "src": "/images/gallery/landscape/gallery_landscape_13.webp",
    "alt": "Jumping outdoors. High energy.",
    "caption": "Jumping outdoors. High energy.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "430",
    "src": "/images/gallery/landscape/gallery_landscape_16.webp",
    "alt": "Two girls posing.",
    "caption": "Two girls posing.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "439",
    "src": "/images/gallery/landscape/gallery_landscape_01.webp",
    "alt": "Girl smiling looking back. Good candid vibe.",
    "caption": "Girl smiling looking back. Good candid vibe.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "442",
    "src": "/images/profil/profil_content_01.webp",
    "alt": "Student presenting at the front.",
    "caption": "Student presenting at the front.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "457",
    "src": "/images/profil/profil_content_02.webp",
    "alt": "Large class sitting on floor. Shows scale of activity.",
    "caption": "Large class sitting on floor. Shows scale of activity.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "467",
    "src": "/images/profil/profil_content_03.webp",
    "alt": "Students listening attentively.",
    "caption": "Students listening attentively.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "471",
    "src": "/images/profil/profil_content_04.webp",
    "alt": "Student speaking into microphone. Active participation.",
    "caption": "Student speaking into microphone. Active participation.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "486",
    "src": "/images/profil/profil_content_05.webp",
    "alt": "Handing out a prize/gift. Rewarding moment.",
    "caption": "Handing out a prize/gift. Rewarding moment.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "489",
    "src": "/images/kkn/kkn_activity_01.webp",
    "alt": "Formal group photo of KKN team.",
    "caption": "Formal group photo of KKN team.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "495",
    "src": "/images/kkn/kkn_activity_02.webp",
    "alt": "Holding 'Stop Bullying' frame. Clear campaign message.",
    "caption": "Holding 'Stop Bullying' frame. Clear campaign message.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "506",
    "src": "/images/gallery/landscape/gallery_landscape_02.webp",
    "alt": "Two girls posing.",
    "caption": "Two girls posing.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "516",
    "src": "/images/profil/profil_story_01.webp",
    "alt": "Strong portrait of KKN member, good for 'Our Team' or KKN section, not general village profile.",
    "caption": "Strong portrait of KKN member, good for 'Our Team' or KKN section, not general village profile.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "523",
    "src": "/images/gallery/landscape/gallery_landscape_03.webp",
    "alt": "Girls crouching by flowers. Nice aesthetics.",
    "caption": "Girls crouching by flowers. Nice aesthetics.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "1001",
    "src": "/images/gallery/portrait/gallery_new_portrait_01.webp",
    "alt": "Portrait warga desa Air Putih",
    "caption": "Potret warga desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  },
  {
    "id": "1002",
    "src": "/images/gallery/portrait/gallery_new_portrait_02.webp",
    "alt": "Potret aktivitas warga desa",
    "caption": "Aktivitas harian warga",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "portrait"
  },
  {
    "id": "1003",
    "src": "/images/home/bersamawarga10.webp",
    "alt": "Anak-anak Desa Air Putih",
    "caption": "Generasi masa depan",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "2000",
    "src": "/images/gallery/portrait/gallery_new_portrait_2000.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "2001",
    "src": "/images/gallery/portrait/gallery_new_portrait_2001.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "3000",
    "src": "/images/gallery/portrait/gallery_new_portrait_3000.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "3001",
    "src": "/images/gallery/portrait/gallery_new_portrait_3001.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5000",
    "src": "/images/gallery/portrait/gallery_new_portrait_5000.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5001",
    "src": "/images/gallery/portrait/gallery_new_portrait_5001.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5002",
    "src": "/images/gallery/portrait/gallery_new_portrait_5002.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5003",
    "src": "/images/gallery/portrait/gallery_new_portrait_5003.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5004",
    "src": "/images/gallery/portrait/gallery_new_portrait_5004.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5005",
    "src": "/images/gallery/portrait/gallery_new_portrait_5005.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5006",
    "src": "/images/gallery/portrait/gallery_new_portrait_5006.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5007",
    "src": "/images/gallery/portrait/gallery_new_portrait_5007.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5008",
    "src": "/images/gallery/portrait/gallery_new_portrait_5008.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5009",
    "src": "/images/gallery/portrait/gallery_new_portrait_5009.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5010",
    "src": "/images/gallery/portrait/gallery_new_portrait_5010.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5011",
    "src": "/images/gallery/portrait/gallery_new_portrait_5011.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5012",
    "src": "/images/gallery/portrait/gallery_new_portrait_5012.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5013",
    "src": "/images/gallery/portrait/gallery_new_portrait_5013.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5014",
    "src": "/images/gallery/portrait/gallery_new_portrait_5014.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5015",
    "src": "/images/gallery/portrait/gallery_new_portrait_5015.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5016",
    "src": "/images/gallery/portrait/gallery_new_portrait_5016.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5017",
    "src": "/images/gallery/portrait/gallery_new_portrait_5017.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5018",
    "src": "/images/gallery/portrait/gallery_new_portrait_5018.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5019",
    "src": "/images/gallery/portrait/gallery_new_portrait_5019.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5020",
    "src": "/images/gallery/portrait/gallery_new_portrait_5020.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5021",
    "src": "/images/gallery/portrait/gallery_new_portrait_5021.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5022",
    "src": "/images/gallery/portrait/gallery_new_portrait_5022.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5023",
    "src": "/images/gallery/portrait/gallery_new_portrait_5023.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5024",
    "src": "/images/gallery/portrait/gallery_new_portrait_5024.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5025",
    "src": "/images/gallery/portrait/gallery_new_portrait_5025.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5026",
    "src": "/images/gallery/portrait/gallery_new_portrait_5026.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5027",
    "src": "/images/gallery/portrait/gallery_new_portrait_5027.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5028",
    "src": "/images/gallery/portrait/gallery_new_portrait_5028.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
  ,{
    "id": "5029",
    "src": "/images/gallery/portrait/gallery_new_portrait_5029.webp",
    "alt": "Potret warga dan desa",
    "caption": "Potret kehidupan desa",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "portrait"
  }
];

