// Auto-generated by script from FINAL_PHOTO_SELECTION.csv
export type PhotoCategory = 'Semua' | 'Masyarakat' | 'Kegiatan' | 'Pendidikan' | 'KKN';

export interface Photo {
  id: string;
  src: string;
  alt: string;
  caption: string;
  category: PhotoCategory;
  orientation?: 'landscape' | 'portrait' | 'square';
  date?: string;
}

export const GALLERY_PHOTOS: Photo[] = [
  {
    "id": "002",
    "src": "/images/background/background_01.jpg",
    "alt": "Tree branches. Good texture.",
    "caption": "Tree branches. Good texture.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "004",
    "src": "/images/background/background_02.jpg",
    "alt": "Tree silhouette against sky. Perfect for text overlay.",
    "caption": "Tree silhouette against sky. Perfect for text overlay.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "008",
    "src": "/images/profil/profil_story_02.jpg",
    "alt": "Nice candid portrait showing village environment.",
    "caption": "Nice candid portrait showing village environment.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "012",
    "src": "/images/kkn/kkn_activity_07.jpg",
    "alt": "Gotong royong activity (sweeping). Directly shows pengabdian.",
    "caption": "Gotong royong activity (sweeping). Directly shows pengabdian.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "014",
    "src": "/images/gallery/landscape/gallery_landscape_09.jpg",
    "alt": "Little girl peeking. Great human interest.",
    "caption": "Little girl peeking. Great human interest.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "016",
    "src": "/images/supporting/supporting_01.jpg",
    "alt": "Boy holding green flag. Good leading lines and action.",
    "caption": "Boy holding green flag. Good leading lines and action.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "019",
    "src": "/images/kkn/kkn_activity_08.jpg",
    "alt": "Carrying items together. Teamwork vibe.",
    "caption": "Carrying items together. Teamwork vibe.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "022",
    "src": "/images/gallery/landscape/gallery_landscape_10.jpg",
    "alt": "Portrait under tree.",
    "caption": "Portrait under tree.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "030",
    "src": "/images/profil/profil_content_06.jpg",
    "alt": "Kids lined up outdoors, good documentation of activity.",
    "caption": "Kids lined up outdoors, good documentation of activity.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "032",
    "src": "/images/kkn/kkn_activity_03.jpg",
    "alt": "Teachers and KKN interacting with students.",
    "caption": "Teachers and KKN interacting with students.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "042",
    "src": "/images/profil/profil_content_07.jpg",
    "alt": "Uniformed kids, shows school environment.",
    "caption": "Uniformed kids, shows school environment.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "060",
    "src": "/images/profil/profil_content_08.jpg",
    "alt": "Active crafting (volcano project). Great storytelling.",
    "caption": "Active crafting (volcano project). Great storytelling.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "072",
    "src": "/images/profil/profil_content_09.jpg",
    "alt": "Proud kid showing artwork.",
    "caption": "Proud kid showing artwork.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "077",
    "src": "/images/gallery/landscape/gallery_landscape_04.jpg",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "083",
    "src": "/images/gallery/landscape/gallery_landscape_05.jpg",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "091",
    "src": "/images/gallery/landscape/gallery_landscape_06.jpg",
    "alt": "Proud artwork portrait.",
    "caption": "Proud artwork portrait.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "107",
    "src": "/images/kkn/kkn_activity_04.jpg",
    "alt": "Great interaction between KKN members and kids.",
    "caption": "Great interaction between KKN members and kids.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "119",
    "src": "/images/home/home_hero_01.jpg",
    "alt": "Large vibrant group shot outdoors. Good energy.",
    "caption": "Large vibrant group shot outdoors. Good energy.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "134",
    "src": "/images/kkn/kkn_activity_05.jpg",
    "alt": "Large group documentation shot on porch.",
    "caption": "Large group documentation shot on porch.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "157",
    "src": "/images/kkn/kkn_activity_06.jpg",
    "alt": "KKN members posing outdoors with kids.",
    "caption": "KKN members posing outdoors with kids.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "160",
    "src": "/images/gallery/landscape/gallery_landscape_07.jpg",
    "alt": "Fun meta photo of KKN taking picture of a kid on slide.",
    "caption": "Fun meta photo of KKN taking picture of a kid on slide.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "166",
    "src": "/images/gallery/landscape/gallery_landscape_08.jpg",
    "alt": "Kid on slide. Playful.",
    "caption": "Kid on slide. Playful.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "173",
    "src": "/images/gallery/landscape/gallery_landscape_11.jpg",
    "alt": "Close up selfie with kids. Very dynamic and fun.",
    "caption": "Close up selfie with kids. Very dynamic and fun.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "176",
    "src": "/images/gallery/landscape/gallery_landscape_12.jpg",
    "alt": "Pinning a badge. Detailed action shot.",
    "caption": "Pinning a badge. Detailed action shot.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "183",
    "src": "/images/home/home_hero_03.jpg",
    "alt": "Excellent close-up portrait of smiling boy. Strong emotional connection.",
    "caption": "Excellent close-up portrait of smiling boy. Strong emotional connection.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "187",
    "src": "/images/profil/profil_content_13.jpg",
    "alt": "Boy focused on coloring. Good composition.",
    "caption": "Boy focused on coloring. Good composition.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "197",
    "src": "/images/kkn/kkn_activity_10.jpg",
    "alt": "Group shot displaying finished artwork.",
    "caption": "Group shot displaying finished artwork.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "209",
    "src": "/images/profil/profil_content_14.jpg",
    "alt": "Top-down view of kids coloring on the floor. Immersive.",
    "caption": "Top-down view of kids coloring on the floor. Immersive.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "227",
    "src": "/images/kkn/kkn_activity_11.jpg",
    "alt": "Another good group documentation.",
    "caption": "Another good group documentation.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "250",
    "src": "/images/gallery/landscape/gallery_landscape_14.jpg",
    "alt": "Guy posing on stairs.",
    "caption": "Guy posing on stairs.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "255",
    "src": "/images/profil/profil_story_03.jpg",
    "alt": "Another warm portrait for humanizing the about page.",
    "caption": "Another warm portrait for humanizing the about page.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "258",
    "src": "/images/gallery/landscape/gallery_landscape_15.jpg",
    "alt": "Girl smiling on playground.",
    "caption": "Girl smiling on playground.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "320",
    "src": "/images/profil/profil_content_12.jpg",
    "alt": "Close up of kids making kolase.",
    "caption": "Close up of kids making kolase.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "325",
    "src": "/images/home/home_hero_02.jpg",
    "alt": "Unique top-down angle of kids crafting. Good for creative layout.",
    "caption": "Unique top-down angle of kids crafting. Good for creative layout.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "393",
    "src": "/images/profil/profil_content_10.jpg",
    "alt": "Teaching in front of the class. Essential education shot.",
    "caption": "Teaching in front of the class. Essential education shot.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "402",
    "src": "/images/profil/profil_content_11.jpg",
    "alt": "Boys at desks paying attention.",
    "caption": "Boys at desks paying attention.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "410",
    "src": "/images/kkn/kkn_activity_09.jpg",
    "alt": "Candid shot of KKN members relaxing by bikes.",
    "caption": "Candid shot of KKN members relaxing by bikes.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "420",
    "src": "/images/gallery/landscape/gallery_landscape_13.jpg",
    "alt": "Jumping outdoors. High energy.",
    "caption": "Jumping outdoors. High energy.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "430",
    "src": "/images/gallery/landscape/gallery_landscape_16.jpg",
    "alt": "Two girls posing.",
    "caption": "Two girls posing.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "439",
    "src": "/images/gallery/landscape/gallery_landscape_01.jpg",
    "alt": "Girl smiling looking back. Good candid vibe.",
    "caption": "Girl smiling looking back. Good candid vibe.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "442",
    "src": "/images/profil/profil_content_01.jpg",
    "alt": "Student presenting at the front.",
    "caption": "Student presenting at the front.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "457",
    "src": "/images/profil/profil_content_02.jpg",
    "alt": "Large class sitting on floor. Shows scale of activity.",
    "caption": "Large class sitting on floor. Shows scale of activity.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "467",
    "src": "/images/profil/profil_content_03.jpg",
    "alt": "Students listening attentively.",
    "caption": "Students listening attentively.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "471",
    "src": "/images/profil/profil_content_04.jpg",
    "alt": "Student speaking into microphone. Active participation.",
    "caption": "Student speaking into microphone. Active participation.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "486",
    "src": "/images/profil/profil_content_05.jpg",
    "alt": "Handing out a prize/gift. Rewarding moment.",
    "caption": "Handing out a prize/gift. Rewarding moment.",
    "category": "Pendidikan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "489",
    "src": "/images/kkn/kkn_activity_01.jpg",
    "alt": "Formal group photo of KKN team.",
    "caption": "Formal group photo of KKN team.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "495",
    "src": "/images/kkn/kkn_activity_02.jpg",
    "alt": "Holding 'Stop Bullying' frame. Clear campaign message.",
    "caption": "Holding 'Stop Bullying' frame. Clear campaign message.",
    "category": "KKN",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "506",
    "src": "/images/gallery/landscape/gallery_landscape_02.jpg",
    "alt": "Two girls posing.",
    "caption": "Two girls posing.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "516",
    "src": "/images/profil/profil_story_01.jpg",
    "alt": "Strong portrait of KKN member, good for 'Our Team' or KKN section, not general village profile.",
    "caption": "Strong portrait of KKN member, good for 'Our Team' or KKN section, not general village profile.",
    "category": "Masyarakat",
    "date": "2026",
    "orientation": "landscape"
  },
  {
    "id": "523",
    "src": "/images/gallery/landscape/gallery_landscape_03.jpg",
    "alt": "Girls crouching by flowers. Nice aesthetics.",
    "caption": "Girls crouching by flowers. Nice aesthetics.",
    "category": "Kegiatan",
    "date": "2026",
    "orientation": "landscape"
  }
];
